
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
    console.log('🌱 Starting database seeding...');

    // 1. Create Default Users
    // 1. Create Default Users
    // Super Admin
    const superAdmin = await prisma.user.upsert({
        where: { username: 'super_admin' },
        update: {},
        create: {
            username: 'super_admin',
            role: 'SUPER_ADMIN',
            passwordHash: 'admin_secret_888',
            avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=admin',
            isActive: true
        }
    });
    console.log(`👤 Created User: ${superAdmin.username}`);

    // Solution Architect
    const admin = await prisma.user.upsert({
        where: { username: 'architect_prime' },
        update: {},
        create: {
            username: 'architect_prime',
            role: 'SOLUTION_ARCHITECT',
            passwordHash: 'hashed_secret_123', // In real app, use bcrypt
            avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=architect',
            isActive: true
        }
    });
    console.log(`👤 Created User: ${admin.username}`);

    // 2. Create Flagship Solution: HyperScale AI Studio
    const flagship = await prisma.solution.upsert({
        where: { id: 'SOL-AI-STUDIO-ENT' },
        update: {},
        create: {
            id: 'SOL-AI-STUDIO-ENT',
            title: 'HyperScale AI Studio (Enterprise)',
            description: 'Pixel-perfect replica of Google AI Studio architecture. Features private gRPC-Web tunneling, Firecracker sandboxing, and real-time multimodal streaming. The ultimate PaaS for internal GenAI development.',
            fullOverview: `
# HyperScale AI Studio: The Ultimate GenAI Foundry

## System Architecture
HyperScale AI Studio is a dedicated PaaS environment engineered for high-performance Large Language Model (LLM) interfaces. It replicates the internal tooling used by top-tier AI labs (like Google DeepMind), providing a seamless "Code-to-Model" bridge.

### Core Components
1.  **Unified Proxy Gateway (The "Alkali" Pattern)**:
    -   Single-entry RPC tunneling via \`ProxyUnaryCall\`.
    -   Protocol Buffers (Protobuf) for compact, type-safe data transmission.
    -   Microservice orchestration without exposing internal topology.

2.  **Sandbox Execution Engine**:
    -   **Technology**: Firecracker MicroVMs & gVisor.
    -   **Capabilities**: Executes Python/Node.js code generated by LLMs in <300ms.
    -   **Isolation**: Network-gapped environments with whitelisted PyPI/npm mirroring.

3.  **Real-Time Multimodal Streaming**:
    -   **WebSocket Data Plane**: Bi-directional audio/video streams for "Live" model interaction.
    -   **Device Abstraction**: Virtualizes client-side cameras and microphones for server-side processing.

## Enterprise Features
-   **Data Sovereignty**: Complete data isolation within your Private VPC.
-   **Audit Trails**: Full logging of every prompt, code execution, and model output.
-   **Team Collaboration**: Multi-seat referencing, prompt versioning, and shared context.
      `,
            industry: 'Platform Infrastructure',
            githubRepo: 'ai-360/hyperscale-studio',
            stars: 12500,
            tags: JSON.stringify(['PaaS', 'Infrastructure', 'GenAI', 'Compiler']),
            scenarios: JSON.stringify(['Internal Developer Platform', 'Prompt Engineering', 'Model Finetuning']),
            deploymentModes: JSON.stringify(['EDGE_PRIVATE']),
            deploymentDifficulty: 'High',
            matchScore: 100,

            encryptionLevel: 'SM4',
            tunnelType: 'Cloud-Proxy',
            packageSigned: true,

            price: 15000,
            currency: 'USDT',
            status: 'active',

            qualityScore: 99,
            securityVerdict: 'Military Grade',
            codeMaintainability: 'High',
            isAudited: true,
            auditDate: new Date(),

            executionPlan: JSON.stringify({
                poc: { title: 'Sandbox Validation', description: 'Test code execution isolation', resources: { compute: '4 vCPU', memory: '8GB', network: 'VPC', storage: 'NVMe' }, human: { roles: ['SecOps'], estimatedHours: 20 }, steps: ['Deploy Gateway', 'Run Penetration Test'] },
                production: { title: 'Cluster Rollout', description: 'Full K8s deployment', resources: { compute: '50 Nodes', memory: '1TB', network: '10Gbps', storage: 'Ceph Cluster' }, human: { roles: ['SRE Team'], estimatedHours: 200 }, steps: ['Helm Install', 'Load Balancing', 'DNS Switch'] },
                saas: { title: 'Global Availability', description: 'Multi-region federation', resources: { compute: 'Hybrid Cloud', memory: 'Infinite', network: 'Anycast', storage: 'Geo-Replicated' }, human: { roles: ['Product VP'], estimatedHours: 500 }, steps: ['Federation', 'Compliance', 'Marketing'] }
            }),

            agents: {
                create: [
                    {
                        role: 'Site Reliability Engineer',
                        name: 'Cipher',
                        avatarSeed: 'robot-1',
                        personality: 'Rigorous, paranoid about security, highly efficient.',
                        status: 'AWAKE',
                        saturation: 100,
                        currentTask: 'Monitoring gRPC latency'
                    },
                    {
                        role: 'Solutions Architect',
                        name: 'Architect Prime',
                        avatarSeed: 'robot-2',
                        personality: 'Visionary, structured, obsessed with clean architecture.',
                        status: 'WORKING',
                        saturation: 95,
                        currentTask: 'Designing scaler policies'
                    }
                ]
            }
        }
    });
    console.log(`🚀 Created Flagship: ${flagship.title}`);

    // 3. Create Fallback Mock Solutions
    const ocr = await prisma.solution.upsert({
        where: { id: 'SOL-OCR-PRO' },
        update: {},
        create: {
            id: 'SOL-OCR-PRO',
            title: 'Industrial OCR Vision Pro',
            description: 'High-speed optical character recognition for manufacturing labels and logistics waybills.',
            industry: 'Logistics',
            tags: JSON.stringify(['Computer Vision', 'Logistics']),
            scenarios: JSON.stringify(['Warehouse', 'Sorting']),
            githubRepo: 'ai-360/ocr-pro',
            stars: 842,
            deploymentModes: JSON.stringify(['EDGE_PRIVATE']),
            deploymentDifficulty: 'Medium',

            encryptionLevel: 'AES-256',
            tunnelType: 'Wireguard',
            packageSigned: true,

            price: 5200,
            currency: 'CNY',
            status: 'active',
            qualityScore: 92,
            securityVerdict: 'Safe',
            codeMaintainability: 'Medium',
            isAudited: true,
            auditDate: new Date()
        }
    });
    console.log(`📦 Created Solution: ${ocr.title}`);

    // Smart Retail Solution
    const retail = await prisma.solution.upsert({
        where: { id: 'SOL-SMART-RETAIL' },
        update: {},
        create: {
            id: 'SOL-SMART-RETAIL',
            title: 'Smart Retail Analytics Hub',
            description: 'AI-driven customer behavior analysis and inventory forecasting system for large retail chains.',
            industry: 'Retail',
            tags: JSON.stringify(['Retail', 'Analytics', 'Forecasting']),
            scenarios: JSON.stringify(['Store Heatmaps', 'Stock Prediction']),
            githubRepo: 'ai-360/smart-retail',
            stars: 3200,
            deploymentModes: JSON.stringify(['CLOUD', 'EDGE_PRIVATE']),
            deploymentDifficulty: 'Low',
            matchScore: 85,

            encryptionLevel: 'AES-256',
            tunnelType: 'Cloud-Proxy',
            packageSigned: true,

            price: 8500,
            currency: 'USD',
            status: 'active',
            qualityScore: 88,
            securityVerdict: 'Standard',
            codeMaintainability: 'High',
            isAudited: true,
            auditDate: new Date()
        }
    });

    // Medical Assistant Solution
    const med = await prisma.solution.upsert({
        where: { id: 'SOL-MED-ASSIST' },
        update: {},
        create: {
            id: 'SOL-MED-ASSIST',
            title: 'MediAssist Pro Diagnosis',
            description: 'HIPAA-compliant assistant for preliminary diagnosis and patient triage using specialized medical LLMs.',
            industry: 'Healthcare',
            tags: JSON.stringify(['Healthcare', 'Diagnosis', 'HIPAA']),
            scenarios: JSON.stringify(['Triage', 'Patient History']),
            githubRepo: 'ai-360/medi-assist',
            stars: 5600,
            deploymentModes: JSON.stringify(['EDGE_PRIVATE']),
            deploymentDifficulty: 'High',
            matchScore: 92,

            encryptionLevel: 'FIPS-140-2',
            tunnelType: 'Reverse-SSH',
            packageSigned: true,

            price: 25000,
            currency: 'USD',
            status: 'active',
            qualityScore: 95,
            securityVerdict: 'Critical',
            codeMaintainability: 'High',
            isAudited: true,
            auditDate: new Date()
        }
    });


    // --- FinTech ---
    await prisma.solution.upsert({
        where: { id: 'SOL-FIN-FRAUD' },
        update: {},
        create: {
            id: 'SOL-FIN-FRAUD',
            title: 'SecureFlow Fraud Detection',
            description: 'Real-time transaction anomaly detection api using graph neural networks.',
            industry: 'FinTech',
            tags: JSON.stringify(['FinTech', 'Security', 'Fraud']),
            scenarios: JSON.stringify(['Payment Gateways', 'Bank Audit']),
            githubRepo: 'ai-360/secure-flow',
            stars: 4100,
            deploymentModes: JSON.stringify(['EDGE_PRIVATE']),
            deploymentDifficulty: 'High',
            price: 50000,
            currency: 'USD',
            status: 'active',
            qualityScore: 98,
            securityVerdict: 'Critical',
            codeMaintainability: 'High',
            isAudited: true,
            encryptionLevel: 'FIPS-140-2',
            tunnelType: 'Cloud-Proxy',
            packageSigned: true,
            auditDate: new Date(),
            agents: {
                create: [
                    {
                        role: 'Risk Analyst',
                        name: 'Sentinal AI',
                        avatarSeed: 'robot-fin-1',
                        personality: 'Suspicious of outliers, detail-oriented.',
                        status: 'WORKING',
                        saturation: 99,
                        currentTask: 'Scanning transaction graphs'
                    }
                ]
            }
        }
    });

    await prisma.solution.upsert({
        where: { id: 'SOL-FIN-ALGO' },
        update: {},
        create: {
            id: 'SOL-FIN-ALGO',
            title: 'AlphaTrade Quant Agent',
            description: 'Autonomous trading agent capable of sentiment analysis on news feeds.',
            industry: 'FinTech',
            tags: JSON.stringify(['FinTech', 'Trading', 'NLP']),
            scenarios: JSON.stringify(['Hedge Funds', 'Personal Wealth']),
            githubRepo: 'ai-360/alpha-trade',
            stars: 2900,
            deploymentModes: JSON.stringify(['CLOUD']),
            deploymentDifficulty: 'Medium',
            price: 12000,
            currency: 'USD',
            status: 'active',
            qualityScore: 90,
            securityVerdict: 'High',
            codeMaintainability: 'Medium',
            isAudited: true,
            encryptionLevel: 'AES-256',
            tunnelType: 'Cloud-Proxy',
            packageSigned: true,
            auditDate: new Date(),
            agents: {
                create: [
                    {
                        role: 'Quant Strategist',
                        name: 'AlphaZero',
                        avatarSeed: 'robot-fin-2',
                        personality: 'Aggressive but calculated, cold logic.',
                        status: 'AWAKE',
                        saturation: 92,
                        currentTask: 'Backtesting volatility models'
                    }
                ]
            }
        }
    });

    // --- E-commerce (1 more) ---
    await prisma.solution.upsert({
        where: { id: 'SOL-ECOMM-REC' },
        update: {},
        create: {
            id: 'SOL-ECOMM-REC',
            title: 'PersonalizeAI Recommendation Engine',
            description: 'Boost conversion rates with deep learning personalization models.',
            industry: 'Retail',
            tags: JSON.stringify(['Retail', 'Recommender', 'Deep Learning']),
            scenarios: JSON.stringify(['Online Store', 'App Feed']),
            githubRepo: 'ai-360/personalize-ai',
            stars: 3500,
            deploymentModes: JSON.stringify(['CLOUD']),
            deploymentDifficulty: 'Low',
            price: 3000,
            currency: 'USD',
            status: 'active',
            qualityScore: 93,
            securityVerdict: 'Standard',
            codeMaintainability: 'High',
            isAudited: true,
            encryptionLevel: 'AES-256',
            tunnelType: 'Cloud-Proxy',
            packageSigned: true,
            auditDate: new Date(),
            agents: {
                create: [
                    {
                        role: 'Growth Hacker',
                        name: 'ClickStream',
                        avatarSeed: 'robot-retail-1',
                        personality: 'Obsessed with CTR and conversion funnels.',
                        status: 'WORKING',
                        saturation: 88,
                        currentTask: 'Optimizing user cohorts'
                    }
                ]
            }
        }
    });

    // --- Logistics (1 more) ---
    await prisma.solution.upsert({
        where: { id: 'SOL-LOG-ROUTE' },
        update: {},
        create: {
            id: 'SOL-LOG-ROUTE',
            title: 'OptiRoute Fleet Manager',
            description: 'Dynamic route optimization for logistics fleets using reinforcement learning.',
            industry: 'Logistics',
            tags: JSON.stringify(['Logistics', 'Optimization', 'RL']),
            scenarios: JSON.stringify(['Delivery', 'Freight']),
            githubRepo: 'ai-360/opti-route',
            stars: 2100,
            deploymentModes: JSON.stringify(['CLOUD', 'EDGE_PRIVATE']),
            deploymentDifficulty: 'Medium',
            price: 8000,
            currency: 'USD',
            status: 'active',
            qualityScore: 89,
            securityVerdict: 'Standard',
            codeMaintainability: 'High',
            isAudited: true,
            encryptionLevel: 'AES-256',
            tunnelType: 'Cloud-Proxy',
            packageSigned: true,
            auditDate: new Date(),
            agents: {
                create: [
                    {
                        role: 'Logistics Coordinator',
                        name: 'Dispatcher X',
                        avatarSeed: 'robot-log-1',
                        personality: 'Efficient, hates delays, master of maps.',
                        status: 'AWAKE',
                        saturation: 95,
                        currentTask: 'Re-routing fleet #7'
                    }
                ]
            }
        }
    });

    // --- Manufacturing ---
    await prisma.solution.upsert({
        where: { id: 'SOL-MFG-QC' },
        update: {},
        create: {
            id: 'SOL-MFG-QC',
            title: 'Visionary QC Inspector',
            description: 'Automated visual inspection for assembly lines detecting micro-defects.',
            industry: 'Manufacturing',
            tags: JSON.stringify(['Manufacturing', 'Computer Vision', 'Quality Control']),
            scenarios: JSON.stringify(['Assembly Line', 'Electronics']),
            githubRepo: 'ai-360/visionary-qc',
            stars: 4500,
            deploymentModes: JSON.stringify(['EDGE_PRIVATE']),
            deploymentDifficulty: 'High',
            price: 20000,
            currency: 'USD',
            status: 'active',
            qualityScore: 96,
            securityVerdict: 'Safe',
            codeMaintainability: 'Medium',
            isAudited: true,
            encryptionLevel: 'AES-256',
            tunnelType: 'Wireguard',
            packageSigned: true,
            auditDate: new Date(),
            agents: {
                create: [
                    {
                        role: 'QA Engineer',
                        name: 'Eagle Eye',
                        avatarSeed: 'robot-mfg-1',
                        personality: 'Perfectionist, zero tolerance for defects.',
                        status: 'WORKING',
                        saturation: 99,
                        currentTask: 'Calibrating optical sensors'
                    }
                ]
            }
        }
    });

    await prisma.solution.upsert({
        where: { id: 'SOL-MFG-PREDICT' },
        update: {},
        create: {
            id: 'SOL-MFG-PREDICT',
            title: 'PredictMaint Industrial IoT',
            description: 'Predictive maintenance for heavy machinery using sensor data analysis.',
            industry: 'Manufacturing',
            tags: JSON.stringify(['Manufacturing', 'IoT', 'Predictive Maintenance']),
            scenarios: JSON.stringify(['Factories', 'Power Plants']),
            githubRepo: 'ai-360/predict-maint',
            stars: 3100,
            deploymentModes: JSON.stringify(['EDGE_PRIVATE', 'CLOUD']),
            deploymentDifficulty: 'Medium',
            price: 15000,
            currency: 'USD',
            status: 'active',
            qualityScore: 91,
            securityVerdict: 'Safe',
            codeMaintainability: 'High',
            isAudited: true,
            encryptionLevel: 'AES-256',
            tunnelType: 'Cloud-Proxy',
            packageSigned: true,
            auditDate: new Date(),
            agents: {
                create: [
                    {
                        role: 'Maintenance Chief',
                        name: 'Gearhead',
                        avatarSeed: 'robot-mfg-2',
                        personality: 'Proactive, technical, loves machinery.',
                        status: 'AWAKE',
                        saturation: 90,
                        currentTask: 'Analyzing vibration sensors'
                    }
                ]
            }
        }
    });

    // --- Legal ---
    await prisma.solution.upsert({
        where: { id: 'SOL-LEGAL-REVIEW' },
        update: {},
        create: {
            id: 'SOL-LEGAL-REVIEW',
            title: 'ContractLens AI',
            description: 'Automated contract review and risk flagging helper for legal teams.',
            industry: 'Legal',
            tags: JSON.stringify(['Legal', 'NLP', 'Documents']),
            scenarios: JSON.stringify(['Law Firms', 'Corporate Legal']),
            githubRepo: 'ai-360/contract-lens',
            stars: 1800,
            deploymentModes: JSON.stringify(['CLOUD', 'EDGE_PRIVATE']),
            deploymentDifficulty: 'Medium',
            price: 10000,
            currency: 'USD',
            status: 'active',
            qualityScore: 94,
            securityVerdict: 'High',
            codeMaintainability: 'High',
            isAudited: true,
            encryptionLevel: 'AES-256',
            tunnelType: 'Cloud-Proxy',
            packageSigned: true,
            auditDate: new Date(),
            agents: {
                create: [
                    {
                        role: 'Paralegal AI',
                        name: 'Lex',
                        avatarSeed: 'robot-legal-1',
                        personality: 'Formal, precise, uses latin legal terms.',
                        status: 'WORKING',
                        saturation: 96,
                        currentTask: 'Reviewing NDAs'
                    }
                ]
            }
        }
    });

    await prisma.solution.upsert({
        where: { id: 'SOL-LEGAL-SEARCH' },
        update: {},
        create: {
            id: 'SOL-LEGAL-SEARCH',
            title: 'JurisSearch Pro',
            description: 'Semantic search engine for case law and legal precedents.',
            industry: 'Legal',
            tags: JSON.stringify(['Legal', 'Search', 'RAG']),
            scenarios: JSON.stringify(['Legal Research', 'Litigation']),
            githubRepo: 'ai-360/juris-search',
            stars: 1200,
            deploymentModes: JSON.stringify(['CLOUD']),
            deploymentDifficulty: 'Low',
            price: 5000,
            currency: 'USD',
            status: 'active',
            qualityScore: 88,
            securityVerdict: 'Standard',
            codeMaintainability: 'High',
            isAudited: true,
            encryptionLevel: 'AES-256',
            tunnelType: 'Cloud-Proxy',
            packageSigned: true,
            auditDate: new Date(),
            agents: {
                create: [
                    {
                        role: 'Research Clerk',
                        name: 'CaseFinder',
                        avatarSeed: 'robot-legal-2',
                        personality: 'Curious, thorough, connects dots.',
                        status: 'AWAKE',
                        saturation: 85,
                        currentTask: 'Indexing Supreme Court rulings'
                    }
                ]
            }
        }
    });

    // --- Education ---
    await prisma.solution.upsert({
        where: { id: 'SOL-EDU-TUTOR' },
        update: {},
        create: {
            id: 'SOL-EDU-TUTOR',
            title: 'Socratic Tutor',
            description: 'Personalized 1-on-1 AI tutoring system adapting to student learning pace.',
            industry: 'Education',
            tags: JSON.stringify(['Education', 'Adaptive Learning', 'Agent']),
            scenarios: JSON.stringify(['K12', 'Higher Ed']),
            githubRepo: 'ai-360/socratic-tutor',
            stars: 5200,
            deploymentModes: JSON.stringify(['CLOUD']),
            deploymentDifficulty: 'Low',
            price: 2000,
            currency: 'USD',
            status: 'active',
            qualityScore: 92,
            securityVerdict: 'Child-Safe',
            codeMaintainability: 'High',
            isAudited: true,
            encryptionLevel: 'AES-256',
            tunnelType: 'Cloud-Proxy',
            packageSigned: true,
            auditDate: new Date(),
            agents: {
                create: [
                    {
                        role: 'Tutor',
                        name: 'Socrates',
                        avatarSeed: 'robot-edu-1',
                        personality: 'Patient, encouraging, asks guiding questions.',
                        status: 'WORKING',
                        saturation: 98,
                        currentTask: 'Teaching Calculus 101'
                    }
                ]
            }
        }
    });

    await prisma.solution.upsert({
        where: { id: 'SOL-EDU-ADMIN' },
        update: {},
        create: {
            id: 'SOL-EDU-ADMIN',
            title: 'CampusBrain Admin',
            description: 'AI for administrative tasks, scheduling, and student success prediction.',
            industry: 'Education',
            tags: JSON.stringify(['Education', 'Admin', 'Analytics']),
            scenarios: JSON.stringify(['Universities', 'Schools']),
            githubRepo: 'ai-360/campus-brain',
            stars: 900,
            deploymentModes: JSON.stringify(['CLOUD']),
            deploymentDifficulty: 'Medium',
            price: 6000,
            currency: 'USD',
            status: 'active',
            qualityScore: 85,
            securityVerdict: 'Standard',
            codeMaintainability: 'Medium',
            isAudited: true,
            encryptionLevel: 'AES-256',
            tunnelType: 'Cloud-Proxy',
            packageSigned: true,
            auditDate: new Date(),
            agents: {
                create: [
                    {
                        role: 'Registrar',
                        name: 'Scheduler',
                        avatarSeed: 'robot-edu-2',
                        personality: 'Organized, punctual, loves spreadsheets.',
                        status: 'AWAKE',
                        saturation: 90,
                        currentTask: 'Optimizing class timetables'
                    }
                ]
            }
        }
    });

    // --- AgriTech ---
    await prisma.solution.upsert({
        where: { id: 'SOL-AGRI-CROP' },
        update: {},
        create: {
            id: 'SOL-AGRI-CROP',
            title: 'CropYield AI',
            description: 'Satellite imagery analysis for crop health monitoring and yield estimation.',
            industry: 'AgriTech',
            tags: JSON.stringify(['AgriTech', 'Satellite', 'Vision']),
            scenarios: JSON.stringify(['Large Farms', 'Insurance']),
            githubRepo: 'ai-360/crop-yield',
            stars: 1500,
            deploymentModes: JSON.stringify(['CLOUD']),
            deploymentDifficulty: 'Medium',
            price: 7500,
            currency: 'USD',
            status: 'active',
            qualityScore: 90,
            securityVerdict: 'Standard',
            codeMaintainability: 'High',
            isAudited: true,
            encryptionLevel: 'AES-256',
            tunnelType: 'Cloud-Proxy',
            packageSigned: true,
            auditDate: new Date(),
            agents: {
                create: [
                    {
                        role: 'Agronomist',
                        name: 'GreenThumb',
                        avatarSeed: 'robot-agri-1',
                        personality: 'Earthy, practical, expert on soil health.',
                        status: 'WORKING',
                        saturation: 93,
                        currentTask: 'Analyzing satellite NDVI data'
                    }
                ]
            }
        }
    });

    await prisma.solution.upsert({
        where: { id: 'SOL-AGRI-IOT' },
        update: {},
        create: {
            id: 'SOL-AGRI-IOT',
            title: 'Greenhouse AutoPilot',
            description: 'Fully autonomous greenhouse environment control using IoT and AI.',
            industry: 'AgriTech',
            tags: JSON.stringify(['AgriTech', 'IoT', 'Control']),
            scenarios: JSON.stringify(['Greenhouses', 'Vertical Farming']),
            githubRepo: 'ai-360/greenhouse-pilot',
            stars: 2300,
            deploymentModes: JSON.stringify(['EDGE_PRIVATE']),
            deploymentDifficulty: 'Medium',
            price: 4500,
            currency: 'USD',
            status: 'active',
            qualityScore: 93,
            securityVerdict: 'Safe',
            codeMaintainability: 'High',
            isAudited: true,
            encryptionLevel: 'AES-256',
            tunnelType: 'Wireguard',
            packageSigned: true,
            auditDate: new Date(),
            agents: {
                create: [
                    {
                        role: 'Systems Monitor',
                        name: 'ClimateControl',
                        avatarSeed: 'robot-agri-2',
                        personality: 'Steady, responsive, humidity-obsessed.',
                        status: 'AWAKE',
                        saturation: 99,
                        currentTask: 'Adjusting ventilation systems'
                    }
                ]
            }
        }
    });

    // --- Healthcare (1 more) ---
    await prisma.solution.upsert({
        where: { id: 'SOL-HEALTH-IMAGING' },
        update: {},
        create: {
            id: 'SOL-HEALTH-IMAGING',
            title: 'NeuroScan Radiology',
            description: 'AI assistant for detecting abnormalities in MRI and CT scans.',
            industry: 'Healthcare',
            tags: JSON.stringify(['Healthcare', 'Imaging', 'Computer Vision']),
            scenarios: JSON.stringify(['Hospitals', 'Radiology Centers']),
            githubRepo: 'ai-360/neuro-scan',
            stars: 4800,
            deploymentModes: JSON.stringify(['EDGE_PRIVATE', 'ON_PREM']),
            deploymentDifficulty: 'High',
            price: 35000,
            currency: 'USD',
            status: 'active',
            qualityScore: 97,
            securityVerdict: 'Critical',
            codeMaintainability: 'High',
            isAudited: true,
            encryptionLevel: 'FIPS-140-2',
            tunnelType: 'Reverse-SSH',
            packageSigned: true,
            auditDate: new Date(),
            agents: {
                create: [
                    {
                        role: 'Chief Radiologist',
                        name: 'Dr. Nexus',
                        avatarSeed: 'robot-med-1',
                        personality: 'Precise, empathetic, focused on patient safety.',
                        status: 'AWAKE',
                        saturation: 98,
                        currentTask: 'Analyzing MRI batch #402'
                    },
                    {
                        role: 'Compliance Officer',
                        name: 'HIPAA Guardian',
                        avatarSeed: 'robot-shield-1',
                        personality: 'Strict, rule-abiding, vigilant.',
                        status: 'WORKING',
                        saturation: 100,
                        currentTask: 'Auditing access logs'
                    }
                ]
            }
        }
    });

    console.log('✅ Seeding completed.');
}

main()
    .then(async () => {
        await prisma.$disconnect();
    })
    .catch(async (e) => {
        console.error(e);
        await prisma.$disconnect();
        process.exit(1);
    });
